name: Test cloudflared DoH Install Script with Bats

on: [push, pull_request]

jobs:
  test-cloudflared:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, arm64, armv7l]
    env:
      ARCH: ${{ matrix.arch }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment
        run: sudo apt-get update && sudo apt-get install -y curl wget bats shellcheck

      - name: Run ShellCheck
        run: shellcheck cloudflared-doh-install.sh

      - name: Run Bats tests
        run: bats tests/
